name: Assign Issue to ProjectV2

on:
  issues:
    types: [labeled]

jobs:
  assign-to-project:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Necessary IDs
        id: findIDs
        uses: actions/github-script@v5
        with:
          script: |
            const query = `
              query {
                repository(owner: "Codetechify", name: "codetechify-repo") {
                  id
                  issues(first: 1, labels: ["feature"], orderBy: {field: CREATED_AT, direction: DESC}) {
                    nodes {
                      id
                    }
                  }
                  projectV2(number: YOUR_PROJECT_NUMBER) {
                    id
                  }
                }
              }
            `;
            const result = await github.graphql(query);
            return {
              repositoryId: result.repository.id,
              issueId: result.repository.issues.nodes[0].id,
              projectId: result.repository.projectV2.id
            };

      - name: Assign Issue to ProjectV2
        uses: actions/github-script@v5
        with:
          script: |
            const outputs = ${{ steps.findIDs.outputs }};
            const projectId = outputs.projectId;
            const issueId = outputs.issueId;
            const mutation = `
              mutation {
                addProjectV2ItemById(input: {
                  projectId: "${projectId}",
                  contentId: "${issueId}"
                }) {
                  item {
                    id
                  }
                }
              }
            `;
            await github.graphql(mutation);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
