name: Assign projectV2 to issue

on:
  issues:
    types: [labeled]

jobs:
  create-branch:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch from issue title and update project card
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const graphqlWithAuth = github.graphql.defaults({
              headers: {
                authorization: `token ${secrets.CODETECHIFY_ACCESS_TOKEN}`,
              },
            });

            const title = context.payload.issue.title.toLowerCase().replace(/\s+/g, '_');
            const branchName = `feature/${title}`;

            // Fetch the default branch name and its latest commit SHA using GraphQL
            const repoInfoQuery = `
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  defaultBranchRef {
                    name
                    target {
                      oid
                    }
                  }
                }
              }
            `;

            const repoInfo = await graphqlWithAuth(repoInfoQuery, {
              owner: 'Codetechify',
              repo: 'codetechify-repo'
            });

            const defaultBranch = repoInfo.repository.defaultBranchRef.name;
            const sha = repoInfo.repository.defaultBranchRef.target.oid;

            // Create the new branch using GraphQL
            const createBranchMutation = `
              mutation($owner: String!, $repo: String!, $ref: String!, $sha: String!) {
                createRef(input: { repositoryId: $repo, name: $ref, oid: $sha }) {
                  clientMutationId
                }
              }
            `;

            await graphqlWithAuth(createBranchMutation, {
              owner: 'Codetechify',
              repo: 'codetechify-repo',
              ref: `refs/heads/${branchName}`,
              sha: sha
            });

      - name: Move Issue in Project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const issueId = context.payload.issue.node_id;

            // Define your project column IDs
            const backlogColumnId = 'BACKLOG_COLUMN_ID'; // Replace with actual ID
            const doingColumnId = 'DOING_COLUMN_ID'; // Replace with actual ID

            // GraphQL query to move issue from Backlog to Doing
            const mutation = `
              mutation($issueId: ID!, $columnId: ID!) {
                moveProjectCard(input: {cardId: $issueId, columnId: $columnId}) {
                  clientMutationId
                }
              }
            `;

            // Fetch issue's project card ID
            const cardIdQuery = `
              query($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    projectCards(first: 1) {
                      nodes {
                        id
                      }
                    }
                  }
                }
              }
            `;

            const cardIdResponse = await github.graphql(cardIdQuery, {
              issueId: issueId
            });

            const cardId = cardIdResponse.node.projectCards.nodes[0].id;

            // Execute the mutation
            const response = await github.graphql(mutation, {
              issueId: cardId,
              columnId: doingColumnId
            });
