name: Feature Issue Workflow

on:
  issues:
    types: [labeled]

jobs:
  process-feature-issue:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Issue and Project ID
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const query = `
              query($owner: String!, $repo: String!, $projectNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issues(last: 1, labels: ["feature"]) {
                    nodes {
                      id
                    }
                  }
                  projectV2(number: $projectNumber) {
                    id
                  }
                }
              }
            `;
            const variables = {
              owner: "Codetechify",
              repo: "codetechify-repo",
              projectNumber: 2
            };

            const result = await github.graphql(query, variables);
            console.log("Issue ID: " + result.repository.issues.nodes[0].id);
            console.log("Project ID: " + result.repository.projectV2.id);
