name: Feature Issue Workflow

on:
  issues:
    types: [labeled]

jobs:
  process-feature-issue:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Issue and Project ID and Assign Project to Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const query = `
              query($owner: String!, $repo: String!, $projectNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issues(last: 1, labels: ["feature"]) {
                    nodes {
                      id
                    }
                  }
                  projectV2(number: $projectNumber) {
                    id
                  }
                }
              }
            `;
            const variables = {
              owner: "Codetechify",
              repo: "codetechify-repo",
              projectNumber: 2
            };

            const result = await github.graphql(query, variables);
            const issueId = result.repository.issues.nodes[0].id;
            const projectId = result.repository.projectV2.id;

            console.log("Issue ID: " + issueId);
            console.log("Project ID: " + projectId);

            const mutation = `
              mutation addProjectToIssue($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId,
                  contentId: $contentId
                }) {
                  item {
                    id
                  }
                }
              }
            `;

            const mutationResult = await github.graphql(mutation, {
              projectId: projectId,
              contentId: issueId
            });

            console.log("Project Item ID: " + mutationResult.addProjectV2ItemById.item.id);
