name: Feature Issue Workflow

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add issue to project
        uses: actions/github-script@v5
        with:
          script: |
            const githubToken = process.env.CODETECHIFY_ACCESS_TOKEN;
            const headers = {
              Authorization: `token ${githubToken}`,
              "GraphQL-Features": "projects_next_graphql"
            };

            const query = `
              mutation ($projectId: ID!, $contentId: ID!) {
                addProjectNextItem(input: {projectId: $projectId, contentId: $contentId}) {
                  projectNextItem {
                    id
                  }
                }
              }
            `;

            const variables = {
              projectId: 2,  
              contentId: context.payload.issue.node_id
            };

            await github.graphql(query, variables, headers);
        env:
          CODETECHIFY_ACCESS_TOKEN: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}

      - name: Set issue status to Backlog
        uses: actions/github-script@v5
        with:
          script: |
            const githubToken = process.env.CODETECHIFY_ACCESS_TOKEN;
            const headers = {
              Authorization: `token ${githubToken}`,
              "GraphQL-Features": "projects_next_graphql"
            };

            const mutation = `
              mutation ($itemId: ID!, $fieldId: ID!, $value: String!) {
                updateProjectNextItemField(input: {itemId: $itemId, fieldId
