name: Feature Issue Workflow

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add issue to project
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const query = `
              mutation ($contentId: ID!, $projectId: ID!) {
                addProjectNextItem(input: {contentId: $contentId, projectId: $projectId}) {
                  projectNextItem {
                    id
                  }
                }
              }
            `;

            const issueId = context.payload.issue.node_id;
            const projectId = 'Globally unique project ID';  // Replace with the actual project ID

            await github.graphql(query, {
              contentId: issueId,
              projectId: projectId
            });
