name: Feature Issue Workflow

on:
  issues:
    types: [labeled]

jobs:
  fetch-issue-project-info:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GraphQL Query
        id: graphql
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const query = `
              query($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $number) {
                    id
                    projectV2(number: 2) {
                      id
                    }
                  }
                }
              }
            `;
            const issueNumber = context.issue.number;
            const result = await github.graphql(query, {
              owner: 'Codetchify',
              repo: 'codetechify-repo',
              number: issueNumber
            });
            console.log('Issue ID:', result.repository.issue.id);
            console.log('ProjectV2 ID:', result.repository.issue.projectV2.id);
            core.setOutput('issue_id', result.repository.issue.id);
            core.setOutput('projectV2_id', result.repository.issue.projectV2.id);

      - name: Print Issue and Project Info
        run: |
          echo "Issue ID: ${{ steps.graphql.outputs.issue_id }}"
          echo "ProjectV2 ID: ${{ steps.graphql.outputs.projectV2_id }}"
