name: Update Status and Create Branch

on:
  issues:
    types: [labeled]

jobs:
  update-status-and-create-branch:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'feature') && contains(github.event.issue.labels.*.name, 'doing')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: Codetechify/codetechify-repo
          token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          persist-credentials: true
          ref: main

      - name: Set Branch Name
        id: branch-name
        run: echo "BRANCH_NAME=$(echo '${{ github.event.issue.title }}' | tr ' ' '_')" >> $GITHUB_ENV

      - name: Check if Feature Branch Exists
        id: check-branch
        run: |
          if git ls-remote --heads origin feature/${{ env.BRANCH_NAME }}; then
            echo "Branch exists, skipping creation."
            echo "::set-output name=exists::true"
          else
            echo "Branch does not exist."
            echo "::set-output name=exists::false"
          fi

      - name: Create Feature Branch
        if: steps.check-branch.outputs.exists == 'false'
        run: |
          git checkout -b feature/${{ env.BRANCH_NAME }}
          git push origin feature/${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}

      - name: Get Current Issue Number
        id: get-issue-number
        run: echo "::set-output name=number::${{ github.event.issue.number }}"

      - name: Replace Label on Issue
        if: steps.check-branch.outputs.exists == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.get-issue-number.outputs.number }},
              name: 'doing'
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.get-issue-number.outputs.number }},
              labels: ['isReviewing']
            });
