name: Update Project Status and Create Branch

on:
  issues:
    types: [labeled]

jobs:
  update-status-and-create-branch:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'doing'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Necessary IDs
        uses: actions/github-script@v6
        id: fetch_ids
        with:
          script: |
            const query = `
              query getNecessaryIds($login: String!, $name: String!, $last: Int, $labels: [String!], $number: Int!, $first: Int, $first2: Int) {
                organization(login: $login) {
                  repository(name: $name) {
                    issues(last: $last, labels: $labels) {
                      nodes {
                        id
                      }
                    }
                    projectV2(number: $number) {
                      id
                      fields(first: $first) {
                        nodes {
                          ... on ProjectV2SingleSelectField {
                            id
                            name
                            options {
                              id
                              name
                            }
                          }
                        }
                      }
                      items(first: $first2) {
                        nodes {
                          id
                        }
                      }
                    }
                  }
                }
              }
            `;
            const variables = {
              "login": "Codetechify",
              "name": "codetechify-repo",
              "last": 1,
              "labels": ["feature"],
              "number": 2,
              "first": 10,
              "first2": 10
            };
            const result = await github.graphql(query, variables);
            return result.organization.repository.projectV2.items.nodes[0].id;

      - name: Update Project Status
        uses: actions/github-script@v6
        with:
          script: |
            const mutation = `
              mutation updateStatus($input: UpdateProjectV2ItemFieldValueInput!) {
                updateProjectV2ItemFieldValue(input: $input) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;
            const variables = {
              "input": {
                "projectId": "PVT_kwDOCRRl0s4AamKs",
                "fieldId": "PVTSSF_lADOCRRl0s4AamKszgREJyE",
                "itemId": "${{ steps.fetch_ids.outputs.result }}",
                "value": {
                  "singleSelectOptionId": "47fc9ee4"
                }
              }
            };
            await github.graphql(mutation, variables);

      - name: Create Branch
        run: |
          git checkout -b feature/${{ github.event.issue.title }}
          git push origin feature/${{ github.event.issue.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
