name: Create Pull Request and Update Label

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request-and-update-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          persist-credentials: true

      - name: Check Commit Message Format
        id: commit-check
        run: |
          if [[ "$(git log -1 --pretty=%B)" =~ ^[a-zA-Z]+: ]]; then
            echo "::set-output name=matched::true"
          else
            echo "::set-output name=matched::false"
          fi

      - name: Get Last Issue Number
        id: get-issue
        uses: actions/github-script@v6
        with:
          script: |
            const query = `
              query getLastIssue($login: String!, $name: String!, $last: Int, $labels: [String!]) {
                organization(login: $login) {
                  repository(name: $name) {
                    issues(last: $last, labels: $labels) {
                      nodes {
                        number
                      }
                    }
                  }
                }
              }`;
            const result = await github.graphql(query, {
              login: "Codetechify",
              name: "codetechify-repo",
              last: 1,
              labels: ["feature", "doing"]
            });
            const issueNumber = result.organization.repository.issues.nodes[0].number;
            return issueNumber;
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}

      - name: Fetch Issue Title
        id: fetch-issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = ${{ steps.get-issue.outputs.result }};
            console.log("Issue number: ", issueNumber); // Debugging
            if (!issueNumber) {
              throw new Error('Issue number is undefined or null');
            }
            const issueResponse = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            const issueTitle = issueResponse.data.title;
            return issueTitle;
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          pr_title: ${{ steps.fetch-issue.outputs.result }}
          pr_body: 'Automatically generated pull request. Closes #${{ steps.get-issue.outputs.result }}'
          source_branch: ${{ env.feature_branch }}
          destination_branch: 'main'

      - name: Replace Label and Link PR to Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = ${{ steps.get-issue.outputs.result }};
            console.log("Issue number: ", issueNumber); // Debugging

            async function updateIssueLabels() {
              const labelsResponse = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              const hasDoing = labelsResponse.data.some(label => label.name === 'doing');
              if (hasDoing) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  name: 'doing'
                });
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  labels: ['isReviewing']
                });
              }
            }

            await updateIssueLabels();
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
