name: Issue Based Branch Creation
on:
  issues:
    types: [edited]

jobs:
  create-branch:
    if: github.event.changes.status.from != 'Doing' && github.event.issue.status == 'Doing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Feature Branch
        run: |
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME="feature/$ISSUE_TITLE"
          git branch "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
