name: Issue Status Workflow

on:
  issues:
    types: [edited]

jobs:
  create-branch-on-status:
    if: github.event.issue.projectV2 == 2 && github.event.issue.status == 'Doing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Feature Branch
        run: |
          FEATURE_NAME=$(echo "${{ github.event.issue.title }}" | tr ' ' '-')
          git branch "feature/$FEATURE_NAME"
          git push origin "feature/$FEATURE_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
