name: Create Pull Request and Update Label

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request-and-update-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          persist-credentials: true

      - name: Extract Feature Branch Name and Issue Number
        run: |
          FEATURE_BRANCH="${GITHUB_REF#refs/heads/}"
          ISSUE_NUMBER=$(echo $GITHUB_REF | grep -oP '(?<=feature/)\d+')
          echo "feature_branch=${FEATURE_BRANCH}" >> $GITHUB_ENV
          echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_ENV
          echo "Feature Branch: ${FEATURE_BRANCH}" # Debugging
          echo "Issue Number: ${ISSUE_NUMBER}" # Debugging

      - name: Count Commits in Feature Branch
        id: count-commits
        run: |
          commit_count=$(git rev-list --count HEAD ^main)
          echo "commit_count=$commit_count" >> $GITHUB_ENV
          echo "Number of commits in the feature branch: $commit_count"

      - name: Fetch Issue Title
        if: env.commit_count > 1
        id: fetch-issue
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Issue number: ", process.env.issue_number); // Debugging
            if (!process.env.issue_number) {
              throw new Error('Issue number is undefined');
            }
            const issueResponse = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.issue_number
            });
            const issueTitle = issueResponse.data.title;
            return issueTitle;
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}

      - name: Create Pull Request
        if: env.commit_count > 1
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          pr_title: ${{ steps.fetch-issue.outputs.result }}
          pr_body: 'Automatically generated pull request. Closes #${{ env.issue_number }}'
          source_branch: ${{ env.feature_branch }}
          destination_branch: 'main'

      - name: Replace Label and Link PR to Issue
        if: env.commit_count > 1
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = process.env.issue_number;
            const labelsResponse = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            const hasDoing = labelsResponse.data.some(label => label.name === 'doing');
            if (hasDoing) {
              await github.issues.removeLabel({
                owner:
                  context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  name: 'doing'
                  });
                  await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  labels: ['isReviewing']
                  });
                  // Add any additional steps to update the status here if needed
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
