name: Create Feature Branch from Issue

on:
  issues:
    types: [labeled]

jobs:
  create-branch:
    if: github.event.label.name == 'doing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODETECHIFY_ACCESS_TOKEN }}
          script: |
            const title = context.payload.issue.title.toLowerCase().replace(/\s+/g, '_');
            const branchName = `feature/${title}`;
            const ref = `refs/heads/${branchName}`;

            console.log(`Checking if branch exists: ${branchName}`);

            // Check if the branch already exists
            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`
              });
              console.log(`Branch ${branchName} already exists`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Branch ${branchName} does not exist, creating now`);

                // Fetch the default branch name
                const defaultBranch = await github.rest.repos.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo
                }).then(res => res.data.default_branch);

                // Fetch the latest commit SHA of the default branch
                const sha = await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${defaultBranch}`
                }).then(res => res.data.object.sha);

                // Create the new branch from the latest commit SHA of the default branch
                await github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: ref,
                  sha: sha
                });
                console.log(`Branch created: ${branchName}`);
              } else {
                throw error;
              }
            }
