name: Create Feature Branch from Issue

on:
  issues:
    types: [labeled]

jobs:
  create-branch:
    if: github.event.label.name == 'doing' # Adjust the label name as needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch from issue title
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Extract the title from the issue and format it for branch naming
            const title = context.payload.issue.title.toLowerCase().replace(/\s+/g, '_');
            const branchName = `feature/${title}`;
            const ref = `refs/heads/${branchName}`;

            console.log(`Creating branch: ${branchName}`);

            // Fetch the default branch name
            const defaultBranch = await github.rest.repos.get({
              owner: 'Codetechify',
              repo: 'codetechify-repo'
            }).then(res => res.data.default_branch);

            // Fetch the latest commit SHA of the default branch
            const sha = await github.rest.git.getRef({
              owner: 'Codetechify',
              repo: 'codetechify-repo',
              ref: `heads/${defaultBranch}`
            }).then(res => res.data.object.sha);

            // Create the new branch from the latest commit SHA of the default branch
            await github.rest.git.createRef({
              owner: 'Codetechify',
              repo: 'codetechify-repo',
              ref: ref,
              sha: sha
            });
