name: Issue Automation Workflow

on:
  issues:
    types: [labeled]

jobs:
  issue-automation:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'feature'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies in utils
        run: |
          cd .github/utils
          npm install

      - name: Compile TypeScript
        run: |
          cd .github/utils
          npx tsc

      - name: Run Compiled JavaScript Script
        run: |
          cd .github/utils/dist
          node moveIssueToBacklog.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
